### ISSUE TITLE
[UI] script update inconsistency in table view

### ISSUE THREAD

**Issue by Tharn** [violentmonkey/violentmonkey#1437]
### What is the problem?

The script list in table view will display update status in 2 different places

### How to reproduce it?

1. Add a bunch of scripts
2. Change settings to table view
3. Hit 'update'

### What is the actual result?

![Untitled-1](https://user-images.githubusercontent.com/13466852/145559693-90fdaf8b-972f-4273-a096-8939258c1564.png)

### Environment
- Browser: Firefox
- Browser version: 95.5 x64 No-EME
- Violentmonkey version: 2.13.0
- OS: Windows 10 Pro x64

**Comment by Tharn** [comment]
Having a script without an update url in between (Redirect - Old Reddit) is responsible for this issue.

**Comment by tophf** [comment]
I can't reproduce it in the beta so I guess this is already fixed.

Also make sure you don't have `Custom CSS` in advanced settings.

**Comment by Tharn** [comment]
Can you share the beta .xpi for me to test it as well?

**Comment by tophf** [comment]
I don't have it. You can load beta `zip` as a temporary extension, see our [releases](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by Tharn** [comment]
Ok, I was able to check and the issue is not fixed.

When sorting by execution order (in my case), the script without update URL is in-between two other sets as show in the screenshot, and the issue still occurs.

**Comment by Tharn** [comment]
The script in question is really simple and looks as follows, feel free to use it to test.

```// ==UserScript==
// @name        Redirect - Old Reddit
// @version     1.1
// @description Redirect to Old Redit
// @author      me
// @include     *://reddit.com/*
// @include     *://www.reddit.com/*
// @include     *://amp.reddit.com/*
// @run-at      document-start
// @grant       none
// ==/UserScript==

location.replace(location.href.replace("amp.reddit.com/", "old.reddit.com/"));
location.replace(location.href.replace("reddit.com/", "old.reddit.com/"));
location.replace(location.href.replace("www.reddit.com/", "old.reddit.com/"));

**Comment by tophf** [comment]
I still can't reproduce it. Also, the update status in your first screenshot is not how it looks now. You're either using custom CSS you didn't install the beta properly.

**Comment by Tharn** [comment]
The screenshot is from the current stable, and it looked the same when I tried the beta. I use Firefox with dark theme. No custom CSS.

-- Okay, looks like creating a new FF profile and installing the beta there will always put the update notifications in the same place. If anything is still amiss in the next stable, I'll ping here.
