### ISSUE TITLE
[BUG] 2.13.2 not work  on Firefox Nightly any  version test  on  Firefox Nightly97.0a1

### ISSUE THREAD

**Issue by klcb2010** [violentmonkey/violentmonkey#1612]
- [ ] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [ ] I have searched for existing issues that already reported this problem and found none

**Describe the bug**

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
1. no
2.no
3.  Android 10
 Open the page and make sure the script supports the page. Open the Violent Monkey again, and no script was found. The oil monkey is OK. 

![微信图片_20221014201449](https://user-images.githubusercontent.com/32628414/195844387-6c66a9dd-567e-45d4-ad60-a4aa837cebd3.jpg)

![微信图片_20221014201456](https://user-images.githubusercontent.com/32628414/195844482-5d3aa309-e2c0-4758-be9f-071518e19d57.jpg)

**Comment by tophf** [comment]
AFAIK this is fixed in the latest beta.

**Comment by klcb2010** [comment]
> AFAIK this is fixed in the latest beta.

It can only be install  from https://addons.mozilla.org/en-US/，I'm waiting for the official version

**Comment by tophf** [comment]
@gera2ld, the current master seems good to release to me.

**Comment by tophf** [comment]
I can see it in Android emulator too. Investigating...

**Comment by tophf** [comment]
I found a bug. The next version should be fixed.

**Comment by tophf** [comment]
I also found a way to [test the beta/development versions](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/). It might seem complicated but actually it's simple.

**Comment by AndyandAndy00** [comment]
> **I found a bug. The next version (2.13.4) should be fixed.** I also found a way to [test the beta/development versions](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/). It might seem complicated but actually it's simple.

May I ask when the new version will be released? The method in the link can only temporarily install the extension on the phone for development and testing. Once the USB connection is disconnected, it will become invalid. I've been transitioning to using tempermonkey for my android phone for the past few months, but I still want to keep using violentmonkey because other devices are also using it.

**Comment by binarynoise** [comment]
@tophf 
Please, please release one of the current releases with the fix for android!
Better some bugs in some new features than completely broken.
2.13.4 is two months old now and still not yet released to the public.

**Comment by tophf** [comment]
Only @gera2ld can release it.

**Comment by klcb2010** [comment]
> Only @gera2ld can release it.

也许你可以 fork这个项目，发布最新版本？gera2ld已经很久没有关注github了，他最近的推特是2022年12月10日。

**Comment by binarynoise** [comment]
Finally.
A stable release.
Now we just need to wait for @gera2ld to release it at the add-on store.

**Comment by binarynoise** [comment]
Has finally been released a week ago. Would have been nice if someone notified us.

**Comment by guidomz** [comment]
Hey, guys. Contrary to the info I gathered from the net, you seem to be able to install violentmonkey successfully on the android release of firefox. I have tried several ways to accomplish this task but none have been successful. Can you please tell me how to do it?

**Comment by tophf** [comment]
See this: https://www.google.com/search?q=how+to+install+extension+in+firefox+android+via+collections

**Comment by guidomz** [comment]
@tophf Thanks for the reply. I forgot to mention that my target browser is actually TorBrowser for android, based on Firefox. I guess it will break anonimity if collections were used, which is probably why firefox accounts feature was disabled in TorBrowser.
